### ISSUE TITLE
"go get" (install) on this repository is throwing build error on "!errors.Is(...)" - is it my go version?

### ISSUE THREAD

**Issue by Blasikov** [golang-queue/queue#80]
Hi,

Doing a "go get" (install) on this repository is throwing build errors on "!errors.Is(...)" - is it my go version?

I've got an older version of Go:  go.1.12.1 (win/amd64) - is "errors.Is()" more recent?

I'm relatively new to Go, so please point me in the right direction if I'm being silly...

Thanks.

EDIT:  Oh my... I just found out that go1.13 added error.Is()  LOL!!!

Any sage advice on a workaround? I'm stuck with 1.12 for now.  I'll try to edit the local source in the meantime.

**Comment by appleboy** [comment]
I will create a new section for "Requirement" in the documentation. You should upgrade your go version to 1.12 above. Today the go version is go 1.19
