### ISSUE TITLE
Support Retry with exponential backoff time duration.

### ISSUE THREAD

**Issue by appleboy** [golang-queue/queue#93]

**Comment by benhid** [comment]
We can implement it using [cenkalti/backoff](https://github.com/cenkalti/backoff) as follows:

```Golang
package main

import (
	"context"
	"errors"
	"time"

	"github.com/cenkalti/backoff/v4"
)

func doSomething() error {
	return errors.New("failed")
}

func main() {
	ctx := context.Background()

	retryCount := 10

	bo := backoff.NewExponentialBackOff()
	bo.InitialInterval = 1 * time.Second
	bo.MaxInterval = 10 * time.Second
	bo.MaxElapsedTime = 0
	bo.Reset()

loop:
	for {
		err := doSomething()

		// check error and retry count
		if err == nil || retryCount == 0 {
			break
		}
		retryCount--

		select {
		case <-time.After(bo.NextBackOff()):
		case <-ctx.Done(): // timeout reached
			err = ctx.Err()
			break loop
		}
	}
}
```

(or using `backoff.Retry()` combined with `backoff.WithMaxRetries()` and `backoff.WithContext()`)

We may need to remove [`RetryDelay`](https://github.com/golang-queue/queue/blob/5a517458ad60cb3ae2f722c306de645f73cf5da6/job/job.go#L32) from messages and include `InitialDelay` and `MaxDelay` (`bo.InitialInterval` and `bo.MaxInterval `, respectively). If both values are the same, then use a constant backoff instead.

If you think it's ok, I can submit a PR.

**Comment by appleboy** [comment]
@benhid I implemented the first version using the lightweight package https://github.com/jpillora/backoff

see the detailed information https://github.com/golang-queue/queue/pull/94
